### ISSUE TITLE
No SOURCES given to target: zstd_static

### ISSUE THREAD

**Issue by Un1q32** [mapron/Wuild#15]
fails to build

**Comment by Un1q32** [comment]
had to clone with recusive

**Comment by mapron** [comment]
:D

**Comment by mapron** [comment]
I will think about including submodule update part in the Build instructions in readme, thanks.

**Comment by Un1q32** [comment]
@mapron downloading the source from the release page has the same problem so maybe include a script to clone the repos manually for people who do that

**Comment by mapron** [comment]
> downloading the source from the release page has the same problem

well, source balls made by github, I do not control them. Did not notice GH does not include submodules there, that's unfortunate.

**Comment by mapron** [comment]
I will create an issue to think about it, as I planing to add 1 more submodule anyway.

**Comment by mapron** [comment]
#16 created I will think how to improve it
